### ISSUE TITLE
[BUG] restart broken on pypi release

### ISSUE THREAD

**Issue by cjekel** [LLNL/merlin#273]
## 🐛 Bug Report

**Describe the bug**
Restart not working in PyPi release 1.7.3, but works on default branch. Not sure if you were already aware.

**Work around**
If you installed from pypi, first uninstall, then install from default git branch
```bash
python -m pip uninstall merlin
python -m pip install git+https://github.com/LLNL/merlin
```

**To Reproduce**
1. install merlin from pypi ```python -m pip install merlin```
2. Start a local workflow... ```merlin run --local workflow.yaml```
3. Interrupt merlin with crl+c
4. Restart the workflow... ```merlin -lvl DEBUG restart --local my_previous_study```
5. See error

```Python
[2020-08-25 15:38:28: INFO] Restarting workflow at '/g/g16/jekel1/Documents/sample-metamaterials/homogenization_study_20200825-151237'
[2020-08-25 15:38:28: DEBUG] Traceback (most recent call last):
  File "/g/g16/jekel1/.conda/envs/pytorchCPU/lib/python3.6/site-packages/merlin/main.py", line 737, in main
    args.func(args)
  File "/g/g16/jekel1/.conda/envs/pytorchCPU/lib/python3.6/site-packages/merlin/main.py", line 207, in process_restart
    study = MerlinStudy(filepath, restart_dir=restart_dir)
  File "/g/g16/jekel1/.conda/envs/pytorchCPU/lib/python3.6/site-packages/merlin/study/study.py", line 97, in __init__
    self.label_clash_error()
  File "/g/g16/jekel1/.conda/envs/pytorchCPU/lib/python3.6/site-packages/merlin/study/study.py", line 144, in label_clash_error
    if label in self.original_spec.globals:
TypeError: argument of type 'NoneType' is not iterable

[2020-08-25 15:38:28: ERROR] argument of type 'NoneType' is not iterable
```

**Expected behavior**
Restart runs.

**Please answer these questions to help us pinpoint the problem**
- Does the problem occur in `merlin run --local` mode, distributed mode or neither? **Both**
- If a distributed problem, which backend and queue servers are you using? How are they configured? **celery** 
- On what machines/architectures are you running merlin? Is this bug on a specific machine or can you reproduce it elsewhere? **quartz.llnl.gov**

**Please run `merlin info` and paste the results here:**
let me know if needed...

**Additional context**
n/a

**Comment by ben-bay** [comment]
Thanks, this is very helpful. You say this bug is already fixed on the `develop` branch?

**Comment by cjekel** [comment]
Yes, I'm not running into any issues using the develop branch.

**Comment by ben-bay** [comment]
Great. Then I'll update our pypi release today so future users can avoid this. Again, thanks.

**Comment by ben-bay** [comment]
@cjekel version 1.7.4 is now released on pypi.
